<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dessins</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js" defer></script>
    <script src="js/main.js" defer></script>
</head>
<body>
    <main id="app" class="container">
        <h1>Dessins</h1>

        <div class="row">
            <section class="col-md-4 border pb-2">
                <form method="post">
                    <fieldset>
                        <legend>Choix de la forme</legend>
                        <div class="form-group">
                            <label for="shape">Forme à dessiner</label>
                            <select v-model="shapeSelected" class="form-control" name="shape" id="shape">
                                <option v-for="shape in shapes">{{ shape }}</option>
                            </select>
                        </div>
                    </fieldset>
                    <fieldset>
                        <legend>Données générales</legend>
                        <div class="form-group">
                            <label for="pos-x">Abscisse (x)</label>
                            <input class="form-control" type="number" name="x" id="pos-x">
                        </div>
                        <div class="form-group">
                            <label for="pos-y">Ordonnée (y)</label>
                            <input class="form-control" type="number" name="y" id="pos-y">
                        </div>
                        <div class="form-group">
                            <label for="color">Couleur</label>
                            <input class="form-control" type="color" name="color" id="color">
                        </div>
                        <div class="form-group">
                            <label for="opacity">Opacité</label>
                            <input class="form-control" type="number" step="0.1" value="1" max="1" min="0" name="opacity" id="opacity">
                        </div>
                    </fieldset>
                    <fieldset>
                        <legend>Données Spécifiques</legend>
                        <section v-show="shapeSelected === 'Rectangle'">
                            <div class="form-group">
                                <label for="rectangle-width">Largeur</label>
                                <input class="form-control" type="number" id="rectangle-width" name="width">
                            </div>
                            <div class="form-group">
                                <label for="rectangle-height">Hauteur</label>
                                <input class="form-control" type="number" id="rectangle-height" name="height">
                            </div>
                        </section>
                        <section v-show="shapeSelected === 'Ellipse'">
                            <div class="form-group">
                                <label for="rx">Rayon axe x</label>
                                <input class="form-control" type="number" id="rx" name="rx">
                            </div>
                            <div class="form-group">
                                <label for="ry">Rayon axe y</label>
                                <input class="form-control" type="number" id="ry" name="ry">
                            </div>
                        </section>
                    </fieldset>
                    <button class="btn btn-primary">Enregistrer</button>
                </form>
            </section>
            <section class="col-md-8">
                <?= $container->render() ?>
            </section>
        </div>
    </main>
</body>
</html>